export const BOOK_ROOM = "BOOK_ROOM";

export const LOADING_BOOKINGS = "LOADING_BOOKINGS";
export const LOAD_BOOKINGS = "LOAD_BOOKINGS";
export const BOOKING_LOAD_FAILED = "BOOKING_LOAD_FAILED";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_FAILED = "CATEGORIES_FAILED";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";